// scripts/migrate.js
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  "https://ixjhyzzocdsufcqgbbvf.supabase.co",
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4amh5enpvY2RzdWZjcWdiYnZmIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjkwNzg3MywiZXhwIjoyMDg4NDgzODczfQ.XGF19V_I6os4rBGzv3xGFTayBWu6mcXYLyC91HD2aUk"
);

// Cole aqui todo o array do seu produtos.js (só o array, sem o export)
const produtos = [
   {
    id: "000468",
    nome: "AMSTEL 600 ML",
    categoria: "cerveja",
    preco: 7.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://imagens.publicocdn.com/imagens/amstel-600ml-1",
    estoque: 99,
    promocao: false,
    fornecedor: "HNK BR INDUSTRIA DE",
    ean: "7896045504541",
  },
  {
    id: "000374",
    nome: "AMSTEL ULTRA LONG NECK",
    categoria: "cerveja",
    preco: 5.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61QqQqQqQqL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "HNK BR INDUSTRIA DE",
    ean: "7896045506439",
  },
  {
    id: "000464",
    nome: "AMSTEL LATÃO",
    categoria: "cerveja",
    preco: 5.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61xXxXxXxXL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "BIG MERCEARIA E COME",
    ean: "7896045505340",
  },
  {
    id: "000656",
    nome: "ANTARTICA 600ML",
    categoria: "cerveja",
    preco: 7.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/51YyYyYyYyL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "010152",
    nome: "ANTARTICA PILSEN LATÃO",
    categoria: "cerveja",
    preco: 5.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61ZzZzZzZzL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "7891991009164",
  },
  {
    id: "000489",
    nome: "ANTARTICA SUB ZERO LITRÃO",
    categoria: "cerveja",
    preco: 8.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61AaAaAaAaL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "7891991010436",
  },
  {
    id: "000488",
    nome: "ANTARTICA SUBZERO LATÃO",
    categoria: "cerveja",
    preco: 4.8,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61BbBbBbBbL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "7891991010153",
  },
  {
    id: "010011",
    nome: "BADEN BADEN",
    categoria: "cerveja",
    preco: 13.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61CcCcCcCcL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "010177",
    nome: "BLACK JOKER",
    categoria: "cerveja",
    preco: 19.9,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61DdDdDdDdL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "7898694890716",
  },
  {
    id: "010176",
    nome: "BLACK JOKER",
    categoria: "cerveja",
    preco: 19.9,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61EeEeEeEeL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "7898694890693",
  },
  {
    id: "010178",
    nome: "BLECK JOKER",
    categoria: "cerveja",
    preco: 35.9,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61FfFfFfFfL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "7898694890679",
  },
  {
    id: "000462",
    nome: "BOHEMIA 1L",
    categoria: "cerveja",
    preco: 9.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61GgGgGgGgL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "7891991010467",
  },
  {
    id: "000461",
    nome: "BOHEMIA 600ML",
    categoria: "cerveja",
    preco: 7.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61HhHhHhHhL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "78905344",
  },
  {
    id: "000463",
    nome: "BOHEMIA LATÃO",
    categoria: "cerveja",
    preco: 5.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61IiIiIiIiL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "7891991014236",
  },
  {
    id: "000432",
    nome: "BOHEMIA LITRINHO",
    categoria: "cerveja",
    preco: 3.2,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61JjJjJjJjL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "7891991013772",
  },
  {
    id: "8000663",
    nome: "BRAHMA 600ML",
    categoria: "cerveja",
    preco: 7.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61KkKkKkKkL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "000529",
    nome: "BRAHMA DUPLOMALTE LATÃO",
    categoria: "cerveja",
    preco: 5.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61LlLlLlLlL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "9999",
    nome: "BRAHMA LATA MALZEBER",
    categoria: "cerveja",
    preco: 5.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61MmMmMmMmL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "7891149101528",
  },
  {
    id: "000440",
    nome: "BRAHMA LATÃO",
    categoria: "cerveja",
    preco: 5.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61NnNnNnNnL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "7891149011001",
  },
  {
    id: "000434",
    nome: "BRAHMA LITRÃO",
    categoria: "cerveja",
    preco: 9.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61OoOoOoOoL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "7891149103041",
  },
  {
    id: "000431",
    nome: "BRAHMA LITRINHO",
    categoria: "cerveja",
    preco: 3.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61PpPpPpPpL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "7891149010103",
  },
  {
    id: "000619",
    nome: "BRAHMA ZERO LATA",
    categoria: "cerveja",
    preco: 4.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61QqQqQqQqL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "8000796",
    nome: "BRUTAL",
    categoria: "cerveja",
    preco: 11.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61RrRrRrRrL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "8000832",
    nome: "BRUTAL LATA",
    categoria: "cerveja",
    preco: 8.9,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61SsSsSsSsL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "8000618",
    nome: "BUDWEISER LITRINHO",
    categoria: "cerveja",
    preco: 3.25,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61TtTtTtTtL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "010128",
    nome: "BUDWEISER LATA ZERO",
    categoria: "cerveja",
    preco: 5.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61UuUuUuUuL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "7891991298407",
  },
  {
    id: "010060",
    nome: "BUDWEISER 1L",
    categoria: "cerveja",
    preco: 9.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61VvVvVvVvL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000598",
    nome: "BUDWEISER 600ML",
    categoria: "cerveja",
    preco: 7.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61WwWwWwWwL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000638",
    nome: "BUDWEISER LATÃO",
    categoria: "cerveja",
    preco: 5.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61XxXxXxXxL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "000601",
    nome: "BUDWEISER LONG NECK",
    categoria: "cerveja",
    preco: 5.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61YyYyYyYyL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "8000836",
    nome: "BUDWEISER ZERO LATÃO",
    categoria: "cerveja",
    preco: 6.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61ZzZzZzZzL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CBB CENTRAL BRASILEI",
    ean: "",
  },
  {
    id: "000543",
    nome: "CANTINA DA SERRA",
    categoria: "cerveja",
    preco: 7.9,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61AaAaAaAaL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000584",
    nome: "CARACU LATA",
    categoria: "cerveja",
    preco: 6.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61BbBbBbBbL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "000356",
    nome: "CHOP HALLER 350ML",
    categoria: "cerveja",
    preco: 7.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61CcCcCcCcL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "DISTRIBUIDORA HALLER",
    ean: "7898646710604",
  },
  {
    id: "010127",
    nome: "CHOP DE VINHO PINKMOON",
    categoria: "cerveja",
    preco: 10.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61DdDdDdDdL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "BIG MERCEARIA E COME",
    ean: "7896336809942",
  },
  {
    id: "000652",
    nome: "CHOPPE DE VINHO 710ML",
    categoria: "cerveja",
    preco: 15.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61EeEeEeEeL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000496",
    nome: "COCA 600ML",
    categoria: "cerveja",
    preco: 6.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61FfFfFfFfL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SPAL INDUSTRIA BRASI",
    ean: "7894900011609",
  },
  {
    id: "010066",
    nome: "COCA COLA ZERO 600ML",
    categoria: "cerveja",
    preco: 5.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61GgGgGgGgL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SPAL INDUSTRIA BRASI",
    ean: "",
  },
  {
    id: "8000769",
    nome: "CORONA LATA ZERO 350ML",
    categoria: "cerveja",
    preco: 6.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61HhHhHhHhL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "0002222",
    nome: "CORONA LATÃO",
    categoria: "cerveja",
    preco: 7.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61IiIiIiIiL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CBB CENTRAL BRASILEI",
    ean: "",
  },
  {
    id: "000597",
    nome: "CORONA LONG NECK",
    categoria: "cerveja",
    preco: 7.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61JjJjJjJjL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "8000700",
    nome: "CORONA LONG NECK ZERO",
    categoria: "cerveja",
    preco: 7.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61KkKkKkKkL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "000572",
    nome: "CORTEZANO",
    categoria: "cerveja",
    preco: 22.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61LlLlLlLlL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000615",
    nome: "EISENBAHN IPA LONG NECK",
    categoria: "cerveja",
    preco: 7.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61MmMmMmMmL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "7898367983813",
  },
  {
    id: "8000788",
    nome: "EISERBAN IPA LATA 350ML",
    categoria: "cerveja",
    preco: 6.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61NnNnNnNnL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "8000797",
    nome: "FYS LATA",
    categoria: "cerveja",
    preco: 3.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61OoOoOoOoL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "HNK BR INDUSTRIA DE",
    ean: "",
  },
  {
    id: "010021",
    nome: "GUARANA ANTARTICA 1L",
    categoria: "cerveja",
    preco: 6.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61PpPpPpPpL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "000624",
    nome: "GUARANA ANTARTICA 3L",
    categoria: "cerveja",
    preco: 13.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61QqQqQqQqL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "8000588",
    nome: "GUARANA ANTARTICA ZERO 2L",
    categoria: "cerveja",
    preco: 9.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61RrRrRrRrL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "7891991001373",
  },
  {
    id: "000476",
    nome: "HEINEKEN 600ML",
    categoria: "cerveja",
    preco: 10.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61SsSsSsSsL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "HNK BR INDUSTRIA DE",
    ean: "78905498",
  },
  {
    id: "000480",
    nome: "HEINEKEN LATA ZERO",
    categoria: "cerveja",
    preco: 6.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61TtTtTtTtL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "HNK BR INDUSTRIA DE",
    ean: "7896045506064",
  },
  {
    id: "000477",
    nome: "HEINEKEN LATÃO",
    categoria: "cerveja",
    preco: 6.75,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61UuUuUuUuL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "HNK BR INDUSTRIA DE",
    ean: "7896045506248",
  },
  {
    id: "8000793",
    nome: "HEINEKEN LONG NECK 250ML",
    categoria: "cerveja",
    preco: 6.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61VvVvVvVvL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000478",
    nome: "HEINEKEN LONG NECK",
    categoria: "cerveja",
    preco: 7.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61WwWwWwWwL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "BIG MERCEARIA E COME",
    ean: "78936683",
  },
  {
    id: "000479",
    nome: "HEINEKEN LONG NECK ZERO",
    categoria: "cerveja",
    preco: 7.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61XxXxXxXxL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "HNK BR INDUSTRIA DE",
    ean: "7896045506040",
  },
  {
    id: "010112",
    nome: "ICE CABARE LONG NECK",
    categoria: "cerveja",
    preco: 7.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61YyYyYyYyL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "GRUPO PETROPOLIS",
    ean: "7898377661848",
  },
  {
    id: "8000828",
    nome: "ICE LEEV LONG NECK 275ML",
    categoria: "cerveja",
    preco: 6.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61ZzZzZzZzL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "8000825",
    nome: "IMPERIO PURO MALTE 473ML",
    categoria: "cerveja",
    preco: 4.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61AaAaAaAaL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000546",
    nome: "ITAIPAVA LATA ZERO",
    categoria: "cerveja",
    preco: 4.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61BbBbBbBbL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "GRUPO PETROPOLIS",
    ean: "",
  },
  {
    id: "8000686",
    nome: "ITAIPAVA LATÃO",
    categoria: "cerveja",
    preco: 4.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61CcCcCcCcL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "GRUPO PETROPOLIS",
    ean: "",
  },
  {
    id: "8000774",
    nome: "ITAIPAVA MEGA LATÃO",
    categoria: "cerveja",
    preco: 4.8,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61DdDdDdDdL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "GRUPO PETROPOLIS",
    ean: "",
  },
  {
    id: "000481",
    nome: "KAISER 600ML",
    categoria: "cerveja",
    preco: 5.29,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61EeEeEeEeL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SPAL INDUSTRIA BRASI",
    ean: "78904644",
  },
  {
    id: "000482",
    nome: "KAISER LATÃO",
    categoria: "cerveja",
    preco: 4.25,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61FfFfFfFfL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "BIG MERCEARIA E COME",
    ean: "7896045503414",
  },
  {
    id: "000475",
    nome: "ORIGINAL 600ML",
    categoria: "cerveja",
    preco: 9.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61GgGgGgGgL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "78905351",
  },
  {
    id: "010059",
    nome: "ORIGINAL LATÃO",
    categoria: "cerveja",
    preco: 5.75,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61HhHhHhHhL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "BIG MERCEARIA E COME",
    ean: "7891991295017",
  },
  {
    id: "8000612",
    nome: "ORIGINAL LITRÃO",
    categoria: "cerveja",
    preco: 10.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61IiIiIiIiL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "010106",
    nome: "ORIGINAL LITRINHO",
    categoria: "cerveja",
    preco: 3.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61JjJjJjJjL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "000526",
    nome: "PETRA 600ML",
    categoria: "cerveja",
    preco: 6.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61KkKkKkKkL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000525",
    nome: "PETRA LATÃO",
    categoria: "cerveja",
    preco: 4.25,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61LlLlLlLlL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "GRUPO PETROPOLIS",
    ean: "",
  },
  {
    id: "010201",
    nome: "PROIBIDA LATÃO",
    categoria: "cerveja",
    preco: 3.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61MmMmMmMmL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "DISTRIBUIDORA TODA H",
    ean: "",
  },
  {
    id: "010085",
    nome: "SALINAS 600ML",
    categoria: "cerveja",
    preco: 38.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61NnNnNnNnL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "BIG MERCEARIA E COME",
    ean: "",
  },
  {
    id: "000595",
    nome: "SAN MARINO",
    categoria: "cerveja",
    preco: 5.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61OoOoOoOoL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SANMARIO",
    ean: "",
  },
  {
    id: "000563",
    nome: "SELVAGEM",
    categoria: "cerveja",
    preco: 17.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61PpPpPpPpL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "ALEXANDRE",
    ean: "",
  },
  {
    id: "000557",
    nome: "SERRA MALTE 600ML",
    categoria: "cerveja",
    preco: 9.25,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61QqQqQqQqL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "7891149200405000436",
    nome: "SKOL 600ML",
    categoria: "cerveja",
    preco: 7.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61RrRrRrRrL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "8000811",
    nome: "SKOL BEATS LATA VERMELHA",
    categoria: "cerveja",
    preco: 6.9,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61SsSsSsSsL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "000343",
    nome: "SKOL BEATS GT LONG NECK",
    categoria: "cerveja",
    preco: 8.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61TtTtTtTtL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "7891991301114",
  },
  {
    id: "000438",
    nome: "SKOL BEATS LATA",
    categoria: "cerveja",
    preco: 7.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61UuUuUuUuL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "8000680",
    nome: "SKOL BEATS LATÃO",
    categoria: "cerveja",
    preco: 10.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61VvVvVvVvL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "010054",
    nome: "SKOL BEATS LN AZUL",
    categoria: "cerveja",
    preco: 8.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61WwWwWwWwL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "8000673",
    nome: "SKOL BEATS TROPICAL LATA",
    categoria: "cerveja",
    preco: 7.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61XxXxXxXxL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "000439",
    nome: "SKOL GT LATA",
    categoria: "cerveja",
    preco: 7.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61YyYyYyYyL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "000437",
    nome: "SKOL LATÃO",
    categoria: "cerveja",
    preco: 5.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61ZzZzZzZzL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "7891149103300",
    nome: "SKOL LITRINHO",
    categoria: "cerveja",
    preco: 3.2,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61AaAaAaAaL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "7891149103300",
  },
  {
    id: "000435",
    nome: "SKOL LITRO",
    categoria: "cerveja",
    preco: 9.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61BbBbBbBbL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "7891149102853",
  },
  {
    id: "000600",
    nome: "SPATEN 600ML",
    categoria: "cerveja",
    preco: 9.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61CcCcCcCcL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "010170",
    nome: "SPATEN LATÃO",
    categoria: "cerveja",
    preco: 6.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61DdDdDdDdL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "DISTRIBUIDORA TODA H",
    ean: "7891991303200",
  },
  {
    id: "000535",
    nome: "SPATEN LONG NECK",
    categoria: "cerveja",
    preco: 6.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61EeEeEeEeL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000599",
    nome: "STELLA 600ML",
    categoria: "cerveja",
    preco: 9.25,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61FfFfFfFfL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "000486",
    nome: "STELLA LATÃO",
    categoria: "cerveja",
    preco: 6.25,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61GgGgGgGgL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "BIG MERCEARIA E COME",
    ean: "7891991303309",
  },
  {
    id: "8000710",
    nome: "STELLA LATÃO GOLDE",
    categoria: "cerveja",
    preco: 7.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61HhHhHhHhL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "118000592",
    nome: "STELLA LOG NEC GOD",
    categoria: "cerveja",
    preco: 7.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61IiIiIiIiL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "000487",
    nome: "STELLA LONG NECK",
    categoria: "cerveja",
    preco: 6.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61JjJjJjJjL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CBB CENTRAL BRASILEI",
    ean: "7891991015462",
  },
  {
    id: "000522",
    nome: "TONICA FYS LATA",
    categoria: "cerveja",
    preco: 3.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/61KkKkKkKkL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },

  // ==================== ENERGETICOS ====================
  {
    id: "8000821",
    nome: "BALY LATINHA",
    categoria: "energetico",
    preco: 5.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71LlLlLlLlL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000591",
    nome: "MONSTER LATAO TRAD",
    categoria: "energetico",
    preco: 11.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71MmMmMmMmL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "DISTRIBUIDORA OURO F",
    ean: "",
  },
  {
    id: "000508",
    nome: "ENERGETICO COCO + AÇAI 2L",
    categoria: "energetico",
    preco: 10.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71NnNnNnNnL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "8000799",
    nome: "MONSTER LATA 269ML",
    categoria: "energetico",
    preco: 8.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71OoOoOoOoL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000483",
    nome: "RED BULL 250ML",
    categoria: "energetico",
    preco: 10.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71PpPpPpPpL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "611269991000",
  },
  {
    id: "8000835",
    nome: "XEQUE MATE LATÃO",
    categoria: "energetico",
    preco: 12.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71QqQqQqQqL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "010145",
    nome: "XEQUE MATE LATÃO 362 ML",
    categoria: "energetico",
    preco: 9.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71RrRrRrRrL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "798190225388",
  },

  // ==================== VINHOS ====================
  {
    id: "8000818",
    nome: "ESPUMANTE CAMPO LARGO MOSCATEL",
    categoria: "vinho",
    preco: 19.9,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71SsSsSsSsL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "ALEXANDRE",
    ean: "",
  },
  {
    id: "010001",
    nome: "CAMPO LARGO SUAVE",
    categoria: "vinho",
    preco: 17.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71TtTtTtTtL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "8000739",
    nome: "CHAMPANHA",
    categoria: "vinho",
    preco: 21.9,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71UuUuUuUuL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000567",
    nome: "MARTINI BIANCO",
    categoria: "vinho",
    preco: 45.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71VvVvVvVvL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000541",
    nome: "VINHO CAMPO LARGO",
    categoria: "vinho",
    preco: 17.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71WwWwWwWwL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "BIG MERCEARIA E COME",
    ean: "",
  },
  {
    id: "000538",
    nome: "VINHO CAPINHA",
    categoria: "vinho",
    preco: 15.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71XxXxXxXxL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "7896051202905",
  },
  {
    id: "000539",
    nome: "VINHO PERGOLA 1L",
    categoria: "vinho",
    preco: 24.9,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71YyYyYyYyL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CBB CENTRAL BRASILEI",
    ean: "",
  },

  // ==================== DESTILADOS ====================
  {
    id: "000579",
    nome: "GIN TANQUERAY 1L",
    categoria: "destilado",
    preco: 120.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71ZzZzZzZzL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000506",
    nome: "JACK 2L",
    categoria: "destilado",
    preco: 10.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71AaAaAaAaL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CBB CENTRAL BRASILEI",
    ean: "",
  },
  {
    id: "000575",
    nome: "BALLANTINES",
    categoria: "destilado",
    preco: 100.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71BbBbBbBbL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "8000632",
    nome: "CABARE FIRE 1 L",
    categoria: "destilado",
    preco: 45.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71CcCcCcCcL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000561",
    nome: "CACHAÇA 51 1L",
    categoria: "destilado",
    preco: 15.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71DdDdDdDdL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "8000833",
    nome: "CACHAÇA 88",
    categoria: "destilado",
    preco: 17.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71EeEeEeEeL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "ALEXANDRE",
    ean: "",
  },
  {
    id: "8000633",
    nome: "CACHAÇA CABARE 700ML",
    categoria: "destilado",
    preco: 35.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71FfFfFfFfL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "8000787",
    nome: "CACHAÇA CAÇULINHA 200ML",
    categoria: "destilado",
    preco: 5.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71GgGgGgGgL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "010122",
    nome: "CACHAÇA JEREMIAS",
    categoria: "destilado",
    preco: 32.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71HhHhHhHhL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "ALEXANDRE",
    ean: "7898912719003",
  },
  {
    id: "8000711",
    nome: "CAMPARI 1L",
    categoria: "destilado",
    preco: 65.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71IiIiIiIiL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "DISTRIBUIDORA OURO F",
    ean: "",
  },
  {
    id: "8000759",
    nome: "CANELINHA 900ML",
    categoria: "destilado",
    preco: 18.9,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71JjJjJjJjL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000569",
    nome: "CONHAQUE DREHER",
    categoria: "destilado",
    preco: 21.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71KkKkKkKkL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SPAL INDUSTRIA BRASI",
    ean: "",
  },
  {
    id: "000556",
    nome: "CONHAQUE PRESIDENTE",
    categoria: "destilado",
    preco: 17.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71LlLlLlLlL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "ALEXANDRE",
    ean: "",
  },
  {
    id: "000566",
    nome: "CONHAQUE SÃO JOÃO DA BARRA",
    categoria: "destilado",
    preco: 22.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71MmMmMmMmL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "ALEXANDRE",
    ean: "",
  },
  {
    id: "000578",
    nome: "GIN GORDON",
    categoria: "destilado",
    preco: 70.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71NnNnNnNnL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SPAL INDUSTRIA BRASI",
    ean: "",
  },
  {
    id: "010108",
    nome: "GIN INTENCION",
    categoria: "destilado",
    preco: 19.9,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71OoOoOoOoL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "DISTRIBUIDORA OURO F",
    ean: "7898080663771",
  },
  {
    id: "000490",
    nome: "GUARAPAN",
    categoria: "destilado",
    preco: 8.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71PpPpPpPpL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SPAL INDUSTRIA BRASI",
    ean: "7894900951516",
  },
  {
    id: "8000662",
    nome: "GUARAPAN 220ML",
    categoria: "destilado",
    preco: 3.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71QqQqQqQqL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "8000705",
    nome: "GUARAVITAN COPO",
    categoria: "destilado",
    preco: 3.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71RrRrRrRrL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "8000795",
    nome: "ICE (51)",
    categoria: "destilado",
    preco: 6.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71SsSsSsSsL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000547",
    nome: "ICE SMIRNFF LONG NEC",
    categoria: "destilado",
    preco: 9.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71TtTtTtTtL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "000592",
    nome: "ICE SYN",
    categoria: "destilado",
    preco: 4.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71UuUuUuUuL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "BIG MERCEARIA E COME",
    ean: "",
  },
  {
    id: "000405",
    nome: "ORLOFF",
    categoria: "destilado",
    preco: 35.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71VvVvVvVvL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "7891050000903",
  },
  {
    id: "000565",
    nome: "PARATUDO",
    categoria: "destilado",
    preco: 19.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71WwWwWwWwL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "010110",
    nome: "PASSPORT SCOTCH",
    categoria: "destilado",
    preco: 70.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71XxXxXxXxL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "7891050000101",
  },
  {
    id: "8000690",
    nome: "PINGA DA ROÇA",
    categoria: "destilado",
    preco: 25.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71YyYyYyYyL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "JOSE CARLOS",
    ean: "",
  },
  {
    id: "000576",
    nome: "RED LABEL 1L",
    categoria: "destilado",
    preco: 100.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/71ZzZzZzZzL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CBB CENTRAL BRASILEI",
    ean: "",
  },
  {
    id: "8000798",
    nome: "RUM MONTILLA",
    categoria: "destilado",
    preco: 38.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/72AaAaAaAaL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "8000638",
    nome: "VODKA KRISKOF 1L",
    categoria: "destilado",
    preco: 13.9,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/72BbBbBbBbL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "8000637",
    nome: "VODKA KRISKOF 1L AZUL",
    categoria: "destilado",
    preco: 13.9,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/72CcCcCcCcL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "010071",
    nome: "VODKA KRISKOF 1L BRANCA",
    categoria: "destilado",
    preco: 13.9,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/72DdDdDdDdL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "7896685200193",
  },
  {
    id: "8000636",
    nome: "VODKA KRISKOF 1L VERMELHA",
    categoria: "destilado",
    preco: 13.9,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/72EeEeEeEeL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000581",
    nome: "VODKA SMIRNOFF",
    categoria: "destilado",
    preco: 42.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/72FfFfFfFfL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "010211",
    nome: "WHISKY WHITE HORSE",
    categoria: "destilado",
    preco: 90.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/72GgGgGgGgL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000577",
    nome: "XAROPE DE LIMÃO PORTO RICO",
    categoria: "destilado",
    preco: 12.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/72HhHhHhHhL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "ALEXANDRE",
    ean: "",
  },

  // ==================== REFRIGERANTES ====================
  {
    id: "8000784",
    nome: "SUCO DV MAIS LATA 290ML",
    categoria: "refrigerante",
    preco: 4.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/72IiIiIiIiL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SPAL INDUSTRIA BRASI",
    ean: "",
  },
  {
    id: "8000733",
    nome: "SUCO TIAL 1L PESSÊGO",
    categoria: "refrigerante",
    preco: 8.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/72JjJjJjJjL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CBB CENTRAL BRASILEI",
    ean: "",
  },
  {
    id: "010006",
    nome: "AGUA COM GAS 1,5L",
    categoria: "refrigerante",
    preco: 5.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/72KkKkKkKkL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "iGARAPÉ",
    ean: "",
  },
  {
    id: "000513",
    nome: "AGUA 20 LITROS",
    categoria: "refrigerante",
    preco: 15.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/72LlLlLlLlL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "JMS DISTRIBUIDORA",
    ean: "",
  },
  {
    id: "010067",
    nome: "AGUA 500ML FARDO",
    categoria: "refrigerante",
    preco: 15.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/72MmMmMmMmL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000596",
    nome: "AGUA 5L",
    categoria: "refrigerante",
    preco: 10.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/72NnNnNnNnL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "iGARAPÉ",
    ean: "",
  },
  {
    id: "010220",
    nome: "AGUA COM GAS FARDO",
    categoria: "refrigerante",
    preco: 21.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/72OoOoOoOoL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "00407",
    nome: "AGUA COM GÁS 500ML 01",
    categoria: "refrigerante",
    preco: 3.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/72PpPpPpPpL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "iGARAPÉ",
    ean: "",
  },
  {
    id: "8000681",
    nome: "AGUA COM GAS NESTLE 500ML",
    categoria: "refrigerante",
    preco: 3.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/72QqQqQqQqL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "8000834",
    nome: "ÁGUA CRISTAL 1,5L",
    categoria: "refrigerante",
    preco: 5.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/72RrRrRrRrL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SPAL INDUSTRIA BRASI",
    ean: "",
  },
  {
    id: "000363",
    nome: "AGUA DE COCO QUADRADO 1L",
    categoria: "refrigerante",
    preco: 12.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/72SsSsSsSsL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "7896000593672",
  },
  {
    id: "8000813",
    nome: "ÁGUA DE COCO TIAL 200ML",
    categoria: "refrigerante",
    preco: 2.8,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/72TtTtTtTtL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "8000707",
    nome: "AGUA SÃO LORENÇO 1/5 COM GAS",
    categoria: "refrigerante",
    preco: 5.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/72UuUuUuUuL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CBB CENTRAL BRASILEI",
    ean: "",
  },
  {
    id: "8000600",
    nome: "ÁGUA SÃO LORENÇO 510 ML COM GÁS",
    categoria: "refrigerante",
    preco: 3.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/72VvVvVvVvL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "000616",
    nome: "AGUA SEM GAS 1,5L",
    categoria: "refrigerante",
    preco: 4.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/72WwWwWwWwL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "iGARAPÉ",
    ean: "",
  },
  {
    id: "000587",
    nome: "AGUA SEM GAS 500ML 01",
    categoria: "refrigerante",
    preco: 2.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/72XxXxXxXxL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "iGARAPÉ",
    ean: "",
  },
  {
    id: "8000810",
    nome: "ÁGUA TROPICAL 500ML",
    categoria: "refrigerante",
    preco: 13.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/72YyYyYyYyL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "iGARAPÉ",
    ean: "",
  },
  {
    id: "8000760",
    nome: "BEM CASA 290ML",
    categoria: "refrigerante",
    preco: 18.9,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/72ZzZzZzZzL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "8000703",
    nome: "BEM CASADO 1L",
    categoria: "refrigerante",
    preco: 50.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/73AaAaAaAaL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CBB CENTRAL BRASILEI",
    ean: "",
  },
  {
    id: "8000653",
    nome: "COCA CALA ZERO 200ML",
    categoria: "refrigerante",
    preco: 2.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/73BbBbBbBbL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SPAL INDUSTRIA BRASI",
    ean: "",
  },
  {
    id: "000447",
    nome: "COCA COLA 2L",
    categoria: "refrigerante",
    preco: 11.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/73CcCcCcCcL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "DISTRIBUIDORA TODA H",
    ean: "7894900027013",
  },
  {
    id: "000602",
    nome: "COCA COLA 3L",
    categoria: "refrigerante",
    preco: 16.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/73DdDdDdDdL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SPAL INDUSTRIA BRASI",
    ean: "",
  },
  {
    id: "000594",
    nome: "COCA COLA KS",
    categoria: "refrigerante",
    preco: 69.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/73EeEeEeEeL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "DISTRIBUIDORA TODA H",
    ean: "",
  },
  {
    id: "000617",
    nome: "COCA COLA LATA ZERO",
    categoria: "refrigerante",
    preco: 4.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/73FfFfFfFfL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SPAL INDUSTRIA BRASI",
    ean: "",
  },
  {
    id: "000450",
    nome: "COCA COLA RETORNAVEL 2L",
    categoria: "refrigerante",
    preco: 8.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/73GgGgGgGgL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SPAL INDUSTRIA BRASI",
    ean: "7894900014211",
  },
  {
    id: "000451",
    nome: "COCA COLA ULTRA 1L",
    categoria: "refrigerante",
    preco: 6.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/73HhHhHhHhL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SPAL INDUSTRIA BRASI",
    ean: "7894900015119",
  },
  {
    id: "8000742",
    nome: "COCA COLA ZERO 1L",
    categoria: "refrigerante",
    preco: 7.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/73IiIiIiIiL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SPAL INDUSTRIA BRASI",
    ean: "",
  },
  {
    id: "000631",
    nome: "COCA COLA ZERO 2L",
    categoria: "refrigerante",
    preco: 12.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/73JjJjJjJjL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "DISTRIBUIDORA TODA H",
    ean: "",
  },
  {
    id: "000449",
    nome: "COCA COLA ZERO RETORNAVEL 2L",
    categoria: "refrigerante",
    preco: 8.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/73KkKkKkKkL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SPAL INDUSTRIA BRASI",
    ean: "7894900704211",
  },
  {
    id: "000448",
    nome: "COCA LATA 350ML",
    categoria: "refrigerante",
    preco: 4.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/73LlLlLlLlL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "DISTRIBUIDORA TODA H",
    ean: "7894900010015",
  },
  {
    id: "8000693",
    nome: "COCA ZERO LATA 220ML",
    categoria: "refrigerante",
    preco: 3.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/73MmMmMmMmL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000559",
    nome: "FANTA LARANJA 2L",
    categoria: "refrigerante",
    preco: 9.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/73NnNnNnNnL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "BIG MERCEARIA E COME",
    ean: "",
  },
  {
    id: "010100",
    nome: "FANTA LARANJA LATA",
    categoria: "refrigerante",
    preco: 4.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/73OoOoOoOoL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SPAL INDUSTRIA BRASI",
    ean: "",
  },
  {
    id: "8000664",
    nome: "FANTA MARACUJÁ LATA",
    categoria: "refrigerante",
    preco: 4.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/73PpPpPpPpL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SPAL INDUSTRIA BRASI",
    ean: "",
  },
  {
    id: "000452",
    nome: "FANTA RETORNAVEL 2L",
    categoria: "refrigerante",
    preco: 8.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/73QqQqQqQqL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SPAL INDUSTRIA BRASI",
    ean: "7894900093308",
  },
  {
    id: "000558",
    nome: "FANTA UVA 2L",
    categoria: "refrigerante",
    preco: 9.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/73RrRrRrRrL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SPAL INDUSTRIA BRASI",
    ean: "",
  },
  {
    id: "8000816",
    nome: "FANTA UVA LATA",
    categoria: "refrigerante",
    preco: 4.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/73SsSsSsSsL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "BIG MERCEARIA E COME",
    ean: "",
  },
  {
    id: "010009",
    nome: "FANTA UVA RETORNAVEL",
    categoria: "refrigerante",
    preco: 8.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/73TtTtTtTtL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SPAL INDUSTRIA BRASI",
    ean: "",
  },
  {
    id: "8000631",
    nome: "FANTA ZERO 2L",
    categoria: "refrigerante",
    preco: 9.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/73UuUuUuUuL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000498",
    nome: "GATORADE UNIDADE",
    categoria: "refrigerante",
    preco: 6.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/73VvVvVvVvL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "000606",
    nome: "GUARANÁ 200ML",
    categoria: "refrigerante",
    preco: 2.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/73WwWwWwWwL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "000442",
    nome: "GUARANA ANTATICA 2L",
    categoria: "refrigerante",
    preco: 9.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/73XxXxXxXxL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "BIG MERCEARIA E COME",
    ean: "7891991001342",
  },
  {
    id: "000582",
    nome: "GUARANA LATA 350ML",
    categoria: "refrigerante",
    preco: 3.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/73YyYyYyYyL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "000644",
    nome: "H2O 1,5L",
    categoria: "refrigerante",
    preco: 8.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/73ZzZzZzZzL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "000495",
    nome: "H2O LIMONETO 500ML",
    categoria: "refrigerante",
    preco: 5.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/74AaAaAaAaL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "7892840812850",
  },
  {
    id: "8000812",
    nome: "H2O!350 LATA",
    categoria: "refrigerante",
    preco: 4.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/74BbBbBbBbL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "010207",
    nome: "KAPO MORANGO",
    categoria: "refrigerante",
    preco: 3.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/74CcCcCcCcL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SPAL INDUSTRIA BRASI",
    ean: "",
  },
  {
    id: "010208",
    nome: "KAPO UVA",
    categoria: "refrigerante",
    preco: 3.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/74DdDdDdDdL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SPAL INDUSTRIA BRASI",
    ean: "",
  },
  {
    id: "8000754",
    nome: "KUAT 2L",
    categoria: "refrigerante",
    preco: 7.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/74EeEeEeEeL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SPAL INDUSTRIA BRASI",
    ean: "",
  },
  {
    id: "000564",
    nome: "LEÃO DO NORTE",
    categoria: "refrigerante",
    preco: 17.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/74FfFfFfFfL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "ALEXANDRE",
    ean: "",
  },
  {
    id: "8000776",
    nome: "MATE COURO 200ML",
    categoria: "refrigerante",
    preco: 2.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/74GgGgGgGgL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "ASPIN DISTRIBUIDORA",
    ean: "",
  },
  {
    id: "000493",
    nome: "MATE COURO 2L",
    categoria: "refrigerante",
    preco: 8.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/74HhHhHhHhL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "ASPIN DISTRIBUIDORA",
    ean: "7896478800012",
  },
  {
    id: "000492",
    nome: "MATE COURO ZERO 2L",
    categoria: "refrigerante",
    preco: 8.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/74IiIiIiIiL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "ASPIN DISTRIBUIDORA",
    ean: "7896478800074",
  },
  {
    id: "000634",
    nome: "PEPSI 200ML",
    categoria: "refrigerante",
    preco: 2.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/74JjJjJjJjL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000458",
    nome: "PEPSI 2L",
    categoria: "refrigerante",
    preco: 9.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/74KkKkKkKkL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "7892840800000",
  },
  {
    id: "000459",
    nome: "PEPSI TWIST 2L",
    categoria: "refrigerante",
    preco: 9.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/74LlLlLlLlL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "7892840802714",
  },
  {
    id: "010187",
    nome: "PEPSI ZERO 2L",
    categoria: "refrigerante",
    preco: 9.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/74MmMmMmMmL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "8000603",
    nome: "SCHWEPPES 1,5L",
    categoria: "refrigerante",
    preco: 8.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/74NnNnNnNnL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000460",
    nome: "SODA 2L",
    categoria: "refrigerante",
    preco: 8.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/74OoOoOoOoL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "7891991001359",
  },
  {
    id: "000649",
    nome: "SPRITE 2L",
    categoria: "refrigerante",
    preco: 9.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/74PpPpPpPpL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "BIG MERCEARIA E COME",
    ean: "",
  },
  {
    id: "8000750",
    nome: "SPRITE LATA",
    categoria: "refrigerante",
    preco: 4.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/74QqQqQqQqL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SPAL INDUSTRIA BRASI",
    ean: "",
  },
  {
    id: "8000657",
    nome: "SPRITE LATA ZERO",
    categoria: "refrigerante",
    preco: 4.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/74RrRrRrRrL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SPAL INDUSTRIA BRASI",
    ean: "",
  },
  {
    id: "000429",
    nome: "SPRITE ZERO",
    categoria: "refrigerante",
    preco: 9.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/74SsSsSsSsL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "BIG MERCEARIA E COME",
    ean: "",
  },
  {
    id: "000554",
    nome: "SUCO DEL VALHE MAIS",
    categoria: "refrigerante",
    preco: 10.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/74TtTtTtTtL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "SPAL INDUSTRIA BRASI",
    ean: "",
  },
  {
    id: "010062",
    nome: "SUCO DV MAIS LARANJA 1L",
    categoria: "refrigerante",
    preco: 10.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/74UuUuUuUuL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "010007",
    nome: "SUCO DV MAIS UVA 200ML",
    categoria: "refrigerante",
    preco: 4.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/74VvVvVvVvL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000413",
    nome: "SUCO TIAL MANGA 1L",
    categoria: "refrigerante",
    preco: 8.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/74WwWwWwWwL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "BIG MERCEARIA E COME",
    ean: "",
  },
  {
    id: "000593",
    nome: "SUCO TIAL UVA 330ML",
    categoria: "refrigerante",
    preco: 3.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/74XxXxXxXxL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "7896005310090",
  },
  {
    id: "000509",
    nome: "SUCO TIAL UVA 1L",
    categoria: "refrigerante",
    preco: 8.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/74YyYyYyYyL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "BIG MERCEARIA E COME",
    ean: "",
  },
  {
    id: "000424",
    nome: "SUKITA 200ML",
    categoria: "refrigerante",
    preco: 2.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/74ZzZzZzZzL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000444",
    nome: "SUKITA 2 LITROS UNID",
    categoria: "refrigerante",
    preco: 8.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/75AaAaAaAaL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "7891149440801",
  },
  {
    id: "000491",
    nome: "SUKITA UVA 2L",
    categoria: "refrigerante",
    preco: 8.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/75BbBbBbBbL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "BIG MERCEARIA E COME",
    ean: "7891149102808",
  },
  {
    id: "010053",
    nome: "TAMPICO 2L",
    categoria: "refrigerante",
    preco: 12.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/75CcCcCcCcL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "ASPIN DISTRIBUIDORA",
    ean: "",
  },
  {
    id: "010079",
    nome: "TONICA 1L",
    categoria: "refrigerante",
    preco: 10.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/75DdDdDdDdL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "7891991298513",
  },
  {
    id: "000521",
    nome: "TONICA LATA",
    categoria: "refrigerante",
    preco: 4.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/75EeEeEeEeL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "000523",
    nome: "TONICA SCHWEPPES",
    categoria: "refrigerante",
    preco: 3.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/75FfFfFfFfL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000520",
    nome: "TONICA ZERO",
    categoria: "refrigerante",
    preco: 4.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/75GgGgGgGgL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "8000658",
    nome: "TONICA ZERO 1L",
    categoria: "refrigerante",
    preco: 10.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/75HhHhHhHhL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },

  // ==================== OUTROS ====================
  {
    id: "8000838",
    nome: "AMENDOIM CHAPONES",
    categoria: "outros",
    preco: 1.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/75IiIiIiIiL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "8000819",
    nome: "AMENDUPÃ",
    categoria: "outros",
    preco: 5.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/75JjJjJjJjL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "8000737",
    nome: "BALA ICE KISS",
    categoria: "outros",
    preco: 0.15,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/75KkKkKkKkL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "8000738",
    nome: "BALA MACIA",
    categoria: "outros",
    preco: 0.1,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/75LlLlLlLlL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "8000753",
    nome: "BATATA CROQUES PETISCO",
    categoria: "outros",
    preco: 5.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/75MmMmMmMmL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "8000704",
    nome: "BG",
    categoria: "outros",
    preco: 4.8,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/75NnNnNnNnL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "P&P DISTRIBUIDORA",
    ean: "",
  },
  {
    id: "5211854",
    nome: "BUBBALOO",
    categoria: "outros",
    preco: 0.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/75OoOoOoOoL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "8000716",
    nome: "CHICLETE BUBBALOO MORANGO",
    categoria: "outros",
    preco: 0.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/75PpPpPpPpL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "8000794",
    nome: "CIGARRO JM",
    categoria: "outros",
    preco: 1.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/75QqQqQqQqL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "ALEXANDRE",
    ean: "",
  },
  {
    id: "000403",
    nome: "CIGARRO PF",
    categoria: "outros",
    preco: 2.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/75RrRrRrRrL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "ALEXANDRE",
    ean: "",
  },
  {
    id: "8000768",
    nome: "DOCES",
    categoria: "outros",
    preco: 2.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/75SsSsSsSsL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "KELLY",
    ean: "",
  },
  {
    id: "8000765",
    nome: "GELINHO SABORIZADO",
    categoria: "outros",
    preco: 4.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/75TtTtTtTtL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "000511",
    nome: "GELO 10 KILOS",
    categoria: "outros",
    preco: 15.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/75UuUuUuUuL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "GELÓTIMO",
    ean: "",
  },
  {
    id: "000512",
    nome: "GELO CUBO 4 KILOS",
    categoria: "outros",
    preco: 13.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/75VvVvVvVvL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "GELÓTIMO",
    ean: "",
  },
  {
    id: "000397",
    nome: "HALLS",
    categoria: "outros",
    preco: 2.5,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/75WwWwWwWwL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "010139",
    nome: "IMPERIO LATÃO",
    categoria: "outros",
    preco: 4.25,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/75XxXxXxXxL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "7898915949193",
  },
  {
    id: "8000826",
    nome: "IMPERIO ULTRA LONG NEG 275ML",
    categoria: "outros",
    preco: 5.3,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/75YyYyYyYyL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "8000837",
    nome: "IMPERIO VERDE LONG NEC",
    categoria: "outros",
    preco: 5.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/75ZzZzZzZzL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "",
  },
  {
    id: "8000764",
    nome: "PICOLES",
    categoria: "outros",
    preco: 2.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/76AaAaAaAaL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "VANILDA",
    ean: "",
  },
  {
    id: "7898946780338",
    nome: "PIRULITO",
    categoria: "outros",
    preco: 0.75,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/76BbBbBbBbL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "",
    ean: "7898946780338",
  },
  {
    id: "010232",
    nome: "TORCIDA SABOR QUEIJO 60G",
    categoria: "outros",
    preco: 3.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/76CcCcCcCcL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
  {
    id: "8000642",
    nome: "TREDENT",
    categoria: "outros",
    preco: 3.0,
    precoAntigo: null,
    desconto: null,
    imagem: "https://m.media-amazon.com/images/I/76DdDdDdDdL._AC_SL1500_.jpg",
    estoque: 99,
    promocao: false,
    fornecedor: "CRBS SA -CDL SANTA L",
    ean: "",
  },
];

async function migrate() {
  const rows = produtos.map((p) => ({
    id:        String(p.id),
    name:      p.nome,
    category:  p.categoria,
    price:     p.preco,
    old_price: p.precoAntigo ?? null,
    discount:  p.desconto ?? null,
    image:     p.imagem ?? null,
    stock:     50,
    is_active: true,
    promotion: p.promocao ?? false,
    supplier:  p.fornecedor ?? null,
    ean:       p.ean ?? null,
  }));

  const { error } = await supabase.from("products").upsert(rows);

  if (error) console.error("❌ Erro:", error.message);
  else console.log(`✅ ${rows.length} produtos migrados com sucesso!`);
}

migrate();