[functions.notify-whatsapp]
verify_jwt = false

[functions.find-master-image]
verify_jwt = true

[functions.upload-product-image]
verify_jwt = true

[functions.pdv-sale]
verify_jwt = true

[functions.create-courier]
verify_jwt = true

[functions.mercadopago-webhook]
verify_jwt = false